---
- name: This is my main playbook
  hosts: all
  become: yes
  roles:
    - git
    - apache
    - php
    - composer
    - mysql
  tasks:
    - name: Clone the laravel repository
      git:
        repo: https://github.com/f1amy/laravel-realworld-example-app.git
        dest: /var/www/html/laravel-realworld-example-app
        clone: yes
        update: yes
      ignore_errors: yes

    - name: Move into the Laravel Repository
      shell: cd /var/www/html/laravel-realworld-example-app

    - name: Install Laravel
      community.general.composer:
        command: create-project
        working_dir: /var/www/html/laravel-realworld-example-app
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1

    - name: Change file ownership, group and permissions
      file:
        path: /var/www/html/laravel-realworld-example-app
        owner: www-data
        group: www-data
        mode: '0775'
        recurse: yes

    - name: Set up Apache virtualhost
      template:
        src: files/laravel.conf.j2
        dest: /etc/apache2/sites-available/laravel.conf
      notify: Restart Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      ignore_errors: yes

    - name: Enable new site
      shell: /usr/sbin/a2ensite laravel.conf
      notify: Restart Apache

    - name: Copy the postgresql bash script
      template:
        src: files/postgresql.sh.j2
        dest: /home/ubuntu/postgresql.sh
        mode: 0775
        force: yes
# Run the postgresql script to install and setup postgresql
     - name: Run the postgresql script
      command: bash /home/ubuntu/postgresql.sh

#  New .env file
    - name: Copy the .env file
      template:
        src: files/.env.j2
        dest: /var/www/html/laravel-realworld-example-app/.env
        mode: 0775
        force: yes
# configure web.php
    - name: routes/web.php configuration
      template:
        src: files/web.php.j2
        dest: /var/www/html/laravel-realworld-example-app/routes/web.php
        force: yes

# Run it all
    - name: Generate app key
      command: "/usr/bin/php /var/www/html/laravel-realworld-example-app/artisan key:generate"
      tags: [ 'laravel', 'artisan:key' ]

    - name: Set up app storage link
      command: "/usr/bin/php /var/www/html/laravel-realworld-example-app/artisan storage:link"
      tags: [ 'laravel', 'artisan:storage' ]

    - name: Run Migrations + Seeders
      command: "/usr/bin/php /var/www/html/laravel-realworld-example-app/artisan migrate"
      tags: [ 'laravel', 'artisan:migrate' ]


    - name: Change file ownership, group and permissions
      file:
        path: /var/www/html/laravel-realworld-example-app/storage>
        owner: www-data
        group: www-data
        mode: '0775'
      ignore_errors: yes







  handlers:
    - name: Enable Apache
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
      become: yes

    - name: Start Apache
      ansible.builtin.systemd:
        name: apache2
        state: started
      become: yes

    - name: Restart Apache
      ansible.builtin.systemd:
        name: apache2
        state: restarted
      become: yes

