handlers:
    - name: Enable Apache
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
      become: yes

    - name: Start Apache
      ansible.builtin.systemd:
        name: apache2
        state: started
      become: yes

    - name: Restart Apache
      ansible.builtin.systemd:
        name: apache2
        state: restarted
      become: yes

