---
- name: Update cache
  apt:
    update_cache: yes
  become: yes

- name: Add the packages in sources lists
  command: apt install apt-transport-https lsb-release software-properties-common ca-certificates -y

- name: Add the packages in sources lists
  command: add-apt-repository ppa:ondrej/php -y

- name: Update the apt cache
  apt:
    update_cache: yes

- name: Install php and its dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php8.1
    - php8.1-cli
    - php8.1-common
    - php8.1-imap
    - php8.1-redis
    - php8.1-snmp
    - php8.1-xml
    - php8.1-zip
    - php8.1-mbstring
    - php8.1-curl
    - php8.1-pgsql
  become: yes
